// Deliberately invented data in an explicitly synthetic Excel layout. This is
// compiler/runtime test evidence, never evidence of Walmart workbook compatibility.
import ExcelJS from "exceljs";
import { writeFileSync, mkdirSync } from "node:fs";
import { CompiledGraph, digest } from "../../src/engine/compiled-graph";
const directory = "data/walmart/compiled/5.0.20260703-18_22_27-api";
const graph = new CompiledGraph(directory);
const version = graph.manifest.schemaVersion;
const category = "Skateboard Risers";
const dir = "tests/fixtures/walmart/synthetic";
mkdirSync(dir, { recursive: true });
const values: Record<string, string | number> = {
  "/Orderable/sku": "SYNTHETIC-001",
  "/Orderable/productIdentifiers": JSON.stringify({
    productId: "036000291452",
    productIdType: "UPC",
  }),
  "/Orderable/price": 4.99,
  "/Orderable/ShippingWeight": 1,
  "/Orderable/country_of_origin_substantial_transformation": "United States",
  [`/Visible/${category}/productName`]: "Synthetic riser example",
  [`/Visible/${category}/brand`]: "Fictional Brand",
  [`/Visible/${category}/condition`]: " new ",
  [`/Visible/${category}/shortDescription`]:
    "Fictitious fixture; not for sale.",
  [`/Visible/${category}/keyFeatures`]: JSON.stringify([
    "Synthetic feature A",
    "Synthetic feature B",
    "Synthetic feature C",
  ]),
  [`/Visible/${category}/mainImageUrl`]: "https://example.com/synthetic.png",
  [`/Visible/${category}/isProp65WarningRequired`]: "No",
  [`/Visible/${category}/has_written_warranty`]: "No",
  [`/Visible/${category}/netContent`]: JSON.stringify({
    productNetContentMeasure: 1,
    productNetContentUnit: "Each",
  }),
  [`/Visible/${category}/smallPartsWarnings`]: JSON.stringify([
    "0 - No warning applicable",
  ]),
};
const fields = Object.entries(values).map(([canonicalPath, value]) => ({
  column: canonicalPath.split("/").at(-1)!,
  canonicalPath,
  schemaPath:
    "#/properties/MPItem/items" +
    canonicalPath
      .split("/")
      .slice(1)
      .map((k) => "/properties/" + k)
      .join(""),
  encoding:
    typeof value === "number"
      ? "number"
      : String(value).startsWith("{") || String(value).startsWith("[")
        ? "json"
        : "text",
}));
const mapping = {
  marketplace: "walmart",
  version,
  synthetic: true,
  origin: "SYNTHETIC",
  provenance:
    "Generated by FeedFix to exercise official compiled rules. Not a Walmart workbook.",
  sheet: "Synthetic Schema 27",
  headerRow: 2,
  marker: {
    cell: "A1",
    value: "FEEDFIX SYNTHETIC SCHEMA-27 FIXTURE — NOT A WALMART TEMPLATE",
  },
  compiled: {
    directory,
    sourceSha256: graph.manifest.sourceSha256,
    productType: category,
    feedHeader: { businessUnit: "WALMART_US", locale: "en", version },
  },
  fields,
};
writeFileSync(
  dir + "/schema-27.mapping.json",
  JSON.stringify(mapping, null, 2) + "\n",
);
const wb = new ExcelJS.Workbook();
wb.creator = "FeedFix SYNTHETIC";
wb.created = new Date("2026-01-01T00:00:00Z");
wb.modified = wb.created;
const sheet = wb.addWorksheet(mapping.sheet);
sheet.addRow([mapping.marker.value]);
sheet.addRow(fields.map((f) => f.column));
sheet.addRow(Object.values(values));
sheet.getRow(2).font = { bold: true };
const hidden = wb.addWorksheet("Synthetic metadata", { state: "veryHidden" });
hidden.getCell("A1").value = { formula: "SUM(1,2)", result: 3 };
const buffer = Buffer.from(await wb.xlsx.writeBuffer());
writeFileSync(dir + "/schema-27.xlsx", buffer);
writeFileSync(
  dir + "/schema-27.golden.json",
  JSON.stringify(
    {
      origin: "SYNTHETIC",
      schemaVersion: version,
      provenance: mapping.provenance,
      workbook: "schema-27.xlsx",
      mapping: "schema-27.mapping.json",
      fixtureSha256: digest(buffer),
      expectedErrors: [{ code: "ENUM_NORMALIZE", cell: "H3" }],
      expectedRemainingErrors: [],
      expectedRepairs: [{ cell: "H3", before: " new ", after: "New" }],
      allowedStructuralChanges: [{ sheet: mapping.sheet, cell: "H3" }],
    },
    null,
    2,
  ) + "\n",
);
